### ISSUE TITLE
Nuxt dev failed

### ISSUE THREAD

**Issue by Barbapapazes** [windicss/nuxt-windicss-module#29] opened 2021-03-20 15:59 UTC
On a fresh install, lunching `yarn dev`, I've got this error:

```shell
 ERROR  Failed to compile with 2 errors                                                                                                           friendly-errors 16:57:52


 ERROR  in ./.nuxt/views/app.template.html                                                                                                        friendly-errors 16:57:52

Module parse failed: Unexpected token (1:0)                                                                                                       friendly-errors 16:57:52
File was processed with these loaders:
 * ./node_modules/html-webpack-plugin/lib/loader.js
 * ./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js
You may need an additional loader to handle the result of these loaders.
> <!DOCTYPE html>
| <html {{ HTML_ATTRS }}>
|   <head {{ HEAD_ATTRS }}>
                                                                                                                                                  friendly-errors 16:57:52
error
```

Is this normal ?

version 0.4.4 and 0.4.5

**Comment by ChangJoo-Park** [comment] 2021-03-20 17:07
+1 here


```log
 ERROR  in ./.nuxt/views/app.template.html                                                                                      

Module parse failed: Unexpected token (1:0)                                                                                      
File was processed with these loaders:
 * ./node_modules/html-webpack-plugin/lib/loader.js
 * ./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js
You may need an additional loader to handle the result of these loaders.
> <!DOCTYPE html>
| <html {{ HTML_ATTRS }}>
|   <head {{ HEAD_ATTRS }}>
                                                                                                                               
error                                                                                                                         
```

**Comment by itpropro** [comment] 2021-03-20 17:36
Duplicate of #28 😉

**Closed** 2021-03-21 03:51 UTC

**Comment by harlan-zw** [comment] 2021-03-21 04:22
See duplicate response
