### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by productfrontenddeveloper** [windicss/nuxt-windicss-module#109] opened 2021-07-11 18:25 UTC
reproduction https://github.com/productfrontenddeveloper/bug

`yarn dev`

 ERROR  Failed to compile with 1 errors                                                                                                                                                        friendly-errors 21:21:41

 ERROR  in ./virtual:windi.css                                                                                                                                                                 friendly-errors 21:21:41

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):                                                                                                                          friendly-errors 21:21:41
TypeError: this.getOptions is not a function
    at Object.loader (/ts/node_modules/postcss-loader/dist/index.js:40:24)
                                                                                                                                                                                               friendly-errors 21:21:41
 @ ./virtual:windi.css 4:14-232 15:3-20:5 16:22-240
 @ ./node_modules/nuxt-windicss/dist/template/windicss.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/composition-api/register.js ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

**Comment by productfrontenddeveloper** [comment] 2021-07-11 18:41
remove postcss loader


 ERROR  in ./virtual:windi.css                                                                                                                                                     friendly-errors 21:39:48

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):                                                                                                              friendly-errors 21:39:48
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'order'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (/-ts/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.loader (/-ts/node_modules/postcss-loader/dist/index.js:43:29)
                                                                                                                                                                                   friendly-errors 21:39:48
 @ ./virtual:windi.css 4:14-232 15:3-20:5 16:22-240
 @ ./node_modules/nuxt-windicss/dist/template/windicss.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/composition-api/register.js ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

**Comment by productfrontenddeveloper** [comment] 2021-07-11 19:06
https://github.com/acidjazz/nuxt-tailvue used, 
![CleanShot 2021-07-11 at 22 06 39](https://user-images.githubusercontent.com/38668796/125207307-45dbc500-e294-11eb-9fad-ffc8f29715e1.png)

```
windicss: {
    options(options: any) {
      options.scanOptions.exclude = ['.git', '.github', '.nuxt/**/*']
      options.scanOptions.dirs = [
        './node_modules/vue-tailwind-color-picker/src',
        './node_modules/tv-*/dist/tv-*.umd.min.js',
        './components',
        './pages',
        './layouts',
      ]
      return options
    },
  },
  ```

**Comment by harlan-zw** [comment] 2021-07-22 03:59
Have discussed this on discord and it's a conflict issue with the nuxt storybook module

**Comment by harlan-zw** [comment] 2021-07-24 03:13
Actually playing around with it, it seems to work fine with the storybook module.

**Comment by harlan-zw** [comment] 2021-07-24 03:21
@productfrontenddeveloper So yeah this issue is not a windi issue, you can confirm that by removing the windi dependency and the problem is still there.

The issue seems to be related to multiple different version dependencies for all the css loaders (postcss, postcss-loader, css-loader, etc). You can fix it by requiring the exact version you need similar to https://github.com/nuxt-community/storybook/blob/master/package.json

Going to close this off, if you have any issues that happen only when windi is included please make a new issue.

**Closed by harlan-zw** 2021-07-24 03:21 UTC
